server:
  port: 9000
  servlet:
    context-path: /onLineTools

spring:
  thymeleaf:
    prefix: classpath:/template/
    cache: false #开发过程中建议关闭cache
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
  freemarker:
    cache: false